language: generic
sudo: required
services:
- docker
install: scripts/travis-setup.sh
cache:
  directories:
  - "/opt/anaconda-pkg-cache"
jobs:
  include:
  - stage: Linux
    if: "(type = push) AND ((branch IN (master, bulk)) OR (fork = true))"
    os: linux
    script: scripts/travis-run.sh
  - stage: Linux
    if: type = pull_request
    os: linux
    script: scripts/travis-run.sh
env:
  global:
  - SUBDAGS=1
  - BIOCONDA_UTILS_TAG=master
  - BIOCONDA_UTILS_BUILD_ARGS="--loglevel=info"
  - BIOCONDA_UTILS_LINT_ARGS=
  - MINICONDA_VER="4.3.21"
  - ANACONDA_USER='nyuad-cgsb'
  - GITHUB_USER='nyuad-cgsb'
  - MY_TRAVIS_REPO_SLUG='biosails/biostacks'
  - CONTAINER_NAMESPACE='nyuad_cgsb'
  - CONDA_PKGS_DIRS='/opt/anaconda-pkg-cache'
  - secure: JHMiExNBJUTCd/cSXb7cY6DK4MmxIPO3IBfQAD6fSNOEXJe2KY9b8qAjxPwzKzD2FzQOZ1dln1rJiF/3HeVUEu3QN96PfhuqSeIaICP+m8q5ZHgQIyvHwDc09ne/yip1l6BIDtXCuNw/tYUZh3tgpw+bTve3cGXFiqYopvqMlZ2NcW/thQbpWCsdTnJq1g+Sq6DO3oRZm3WGdfS2sh3mv6TErXhQJi8nqWoNyOl2S6JGHRNOHp5vA11D24cAyxY+f5ezhp6Z3QxWL2mnnEwnazEC1PgcE6nA443R2fQRnF5q+ze42g+lSE3FTelWgwY2Jq5hIZRcov2Wj9H+i5zFDmnf503YZ2YLQ52WXnkPtuYCCOi5Sl7/qALLnjyLYNGoBCTZaONeToNSBs/058teuDZCDSLoLFCLlKnpPf1/FnkpEE8cegedHjvCeo2ffehCCrXiAoelUeAOscq9f7GSGa0UrybQckAhIQpR/J1C+FrOaOoFUXhtpxFFwxT6l36Vnt8i0dW0BKve6WU+DeG84JC5NnoULVK40Rg/VgGaB0qq1rX7+TWPw2kGWGWuAUDy+d6jAa+q41VzXjErmgeh3ftCtqS4TLS8tGGuhXkFj3wn9Z7fHIC0r82OqAQNyzj07hNk0MM/btGlU//bquyTFq4gwT2+jS3t1UqENFvAOA0=
  - secure: BX03MYZvVxOOLCXezmYGytgnpAHuaNh8kwVq2bYShUAAPNECZVPtNiXF+TQSuTfnXMM+9fm9M6dXyvCvbc5S8I5BcWEjqJj0fWvxmayejElySxEnNdH6FCuV0vWIwTzDyTUjiZcio/NaUgKlbhKfCqo85pxwOErHxuJlUILDmzwFQa84UzpFaAK2fEn5yja2GJbWfOmHiormHUz+2itchNPVQKXjhw9uZqnDflrVjhNzmF4+zUCLwiM9V5NRKobVeovRNTNg6sQ8ur5aL97tkR8FQz2Y92uYLfUtly8tzJX3/ytQ6F6kSSlat3rJcLjw5x1+J/kE1jjXvQ0Wj1Uy7qCowTMZ6rsOY3WpUiEas0YsIPYfn382ZnhqKW6OspPIFw+3tYVOv2GZtJPaDjfXCYvC5UC2qIpc/Po25nPA8Z6JgTSw9q0Y1gsn6EA/Auf8RD8SUXgwrxqWe/rT7rrpbOAhlDvM+fsCf666yl4sTe+AeJ36PepJ1H5pMZ82oz+K5Gh6wjj74t4hta/u/bbkd6HK0DIFZ+uHoHLq3sEQc9hq/4ljvy6CCq1S6w3sLd4/PNtHhbYlKywLckID255lkkla+mZegMzVE1VjsKE+tQhbvWkitlhJwbIowIcTmXFBxBZJzyp/8qcVwOhUy8ghSACQ6MWXov0QKW0BXnvqNmQ=
  - secure: jwpTmy+EHGsvVBo4e2auBKrY17niCy7lTfmiNPSpWwVIBALKH8TehRKk3IBnGV0SeWCPgd5JUV6UMBIwJQFM/4vMF9BfJ1o9Z0Rsrw+w6OgV7A4kIDK4aDxohHbCouGEk47LDfGt/tBcD97jfWaHxB7Uj2wgwakVEk9hraBFhajf0IcmZ8FkAqZXDhfc0ePtZZlHhRcRSjsOV2nZOVsiLRPcdLEnR/7+5YgswUNwxnUKDqimt3d8tDYWwnOzbuh9wsiQZt90v8b/ELIsARjx5wDsm9ksIaDi7Wg3BdUZSVX2JZf8lIgH5u1TiLPM1kdCsEila0Qdi+O2oGm7lYv0Y3XiXOjqpJKmWdpaFFlU7cN7CagSBxUzgziEYlHGKoDWjwnl6e20JQunkkVBJBl04PedDOUR2bAy0BumhNfXH0OmZokPJ8VZ226C2NjIWRRWKLyBxYp+k7OSouGdNpr30h22w/rwMY+4BnsHpI80M+LFbtWEhOOXbQd6/0witz/gNpPuG72I96fZnnz0KTRFaUdp6fsC4w5ITMYgmuaFzazhCyU7isP8k3ghdJTNGeY6S9HnRyb3k1SsRZsCP0qB12NEb9dVVc+/Ip0gtju4SurH11bj6fhbaKl0LZogGQHqCnnoBNrHvGmutIHZDPFJC4JysbAtfRsC77p1c7jucGA=
  matrix:
  - SUBDAG=0
matrix:
  fast_finish: true

