{% set name = "gencore_test" %}
{% set version = "1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  skip: True # [osx]

requirements:
  run:
    - perl

test:
  commands:
    - perl --help 2>&1 | grep 'perl'


about:
  home: 'https://cgsb.abudhabi.nyu.edu/'
  license: BSD
  summary: 'Gencore Test Package'
