{% set name = "gencore_rnaseq_alignment" %}
{% set version = "1.0" %}


package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  skip: True # [osx]

requirements:
  run:
  ##Alignment
  - samtools ==1.3.1
  - kallisto ==0.43.0
  - cufflinks-patch ==2.2.1
  - bowtie2 ==2.2.8
  - tophat ==2.1.0
  - star ==2.5.2a

test:
  commands:
    - bowtie2 --help 2>&1 | grep 'bowtie'

about:
  home: 'https://cgsb.abudhabi.nyu.edu/'
  license: BSD
  summary: 'Gencore RnaSeq Module'
