{% set name = "gencore_rnaseq" %}
{% set version = "1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 1
  skip: True # [osx]

requirements:
  run:
  ##Alignment
  - samtools ==1.3.1
  - kallisto ==0.43.0
  # - cufflinks-patch ==2.2.1
  # - bowtie2 ==2.2.8
  # - tophat ==2.1.0
  # - star ==2.5.2a
  # - bcftools ==1.3.1
  # - blat ==35
  # - gatk ==3.6
  # - picard ==2.5.0
  # - prinseq ==0.20.4
  # - vcftools ==0.1.14
  # - bedtools ==2.25.0
  # - vcflib ==1.0.0_rc1
  # - bamtools ==2.4.0
  # - seqtk ==1.2
  ##Downstream processing
  # - r-base
  # - r-essentials
  # - r-cairo
  # - bioconductor-deseq2
  # - bioconductor-edger >=3.14.0
  # - bioconductor-cummerbund >=2.16.0
  # - bioconductor-genomicranges >=1.26.1
  # - bioconductor-gviz >=1.16.5
  # - bioconductor-biovizbase >=1.18.0
  # - bioconductor-s4vectors >=0.12.0
  # - bioconductor-ballgown >=2.2.0
  # - htseq ==0.6.1.post1
  # - hisat2 ==2.0.4
  # - stringtie ==1.3.0

test:
  commands:
    - bowtie2 --help 2>&1 | grep "bowtie"

about:
  home: 'https://cgsb.abudhabi.nyu.edu/'
  license: BSD
  summary: 'Gencore RnaSeq Module'
