{% set name = "gencore_metagenomics" %}
{% set version = "1.0" %}


package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  skip: True # [osx]

requirements:
  run:
      - blat ==35
      - cd-hit ==4.6.4
      - augustus ==3.2.2
      - blast ==2.2.31
      - hmmer ==3.1b2
      - bwa ==0.7.15
      - samtools ==1.3.1
      - bcftools ==1.3.1
      - bedtools ==2.25.0
      - vcftools ==0.1.14
      - vcflib ==1.0.0_rc1
      - bamtools ==2.4.0
      - mawk ==1.3.4
      - seqtk ==1.2
      - pear ==0.9.6
      - bowtie2 ==2.2.8
      - bioconductor-dada2 ==1.0.3
      - mothur ==1.36.1

test:
  commands:
    - samtools --help 2>&1 | grep 'samtools'

about:
  home: 'https://cgsb.abudhabi.nyu.edu/'
  license: BSD
  summary: 'Gencore Metagenomics'
